### ISSUE TITLE
Blender 2.80 support

### ISSUE THREAD

**Issue by ghost** [MattiasFredriksson/Blender-Projection_Ops#1]
Will you port it over to Blender 2.80? I really miss the mesh on mesh projection. Thanks!

**Comment by MattiasFredriksson** [comment]
Hey, short answer is: Yes i'll make a port that will be finished before the end of the week (unless i encounter any major problems).

Long answer is that I've been waiting for 2.8 to be released before i commit time to it. The goal has been to improve it at the same time, but as that seems unlikely for the near future (it'll probably require a month+ of commitment), and since you asked, porting functionality seems critical as release of 2.8 is imminent. Hopefully, the end of the week is an agreeable timeline for 2.8 support  :) .

**Comment by ghost** [comment]
Sure is, to be honest, I'm just trying to see if the crucial addons I use will get support, if not I'll stay on 2.79 for as long as possible. Thanks for your quick response!

**Comment by MattiasFredriksson** [comment]
Support for 2.8 should now be complete and functional, i'll have to excuse myself if it took longer then expected. Installing the addon/script can be done by [downloading](https://github.com/MattiasFredriksson/Blender-Projection_Ops/archive/master.zip) and moving the appropriate version of the 'projection_ops' folder to the script folder in Blender. I do manual testing of the functions, but if you experience any bugs (or just have issues with how some of the functions work; ) just open a new issue and i'll look in to it :)
